### ISSUE TITLE
Implement integer bitmask functions in Rust

### ISSUE THREAD

**Issue by lopopolo** [artichoke/artichoke#1084]
Currently, `Integer#allbits?`, `Integer#anybits?`, and `Integer#nobits?` are implemented in Ruby. These bit masking operations will be cheaper to implement in Rust.

https://github.com/artichoke/artichoke/blob/e13799db9c6a5b91c99509e119753297be91eba6/artichoke-backend/src/extn/core/integer/integer.rb#L8-L47

`Integer#div` will be a useful example to template off of.

The Rust bit is implemented in the `extn::integer::trampoline` module:

https://github.com/artichoke/artichoke/blob/e13799db9c6a5b91c99509e119753297be91eba6/artichoke-backend/src/extn/core/integer/trampoline.rs#L18-L22

and exposed to the Ruby VM in an `mruby` trampoline:

https://github.com/artichoke/artichoke/blob/e13799db9c6a5b91c99509e119753297be91eba6/artichoke-backend/src/extn/core/integer/mruby.rs#L49-L59

and injected into the VM:

https://github.com/artichoke/artichoke/blob/e13799db9c6a5b91c99509e119753297be91eba6/artichoke-backend/src/extn/core/integer/mruby.rs#L13

To match the current implementation, you'll want to convert the argument to an integer with [`implicitly_convert_to_int`](https://artichoke.github.io/artichoke/artichoke_backend/convert/fn.implicitly_convert_to_int.html) like `Integer#[]` does:

https://github.com/artichoke/artichoke/blob/e13799db9c6a5b91c99509e119753297be91eba6/artichoke-backend/src/extn/core/integer/trampoline.rs#L13

To make sure this conversion is the right thing to do, try this code in MRI to see what happens:

```
class A; def to_int; 0xFF; end; end
10.anybits?(A.new)
```

If this gives the same answer as `10.anybits?(0xFF)`, then we should be using the implicit converter, which can delegate to `#to_int`.

Remember to remove the definitions of these functions in Ruby.

To ensure the Rust functions you're creating are being called, you can print to stdout by adding something like:

```rust
println!("calling card from Rust code!");
```

**Comment by lopopolo** [comment]
Whoever picks this up might want to expose these bitmasking functions on the `Integer` wrapper:

https://github.com/artichoke/artichoke/blob/e13799db9c6a5b91c99509e119753297be91eba6/artichoke-backend/src/extn/core/integer/mod.rs#L65

**Comment by sudopluto** [comment]
checked with irb, seems like implicit conversion is done.

i think i got the bitmap functions working, just need to write tests.

tested manually by comparing airb and irb output.

edit: should I try to abstract out these predicates? can probably pass in predicate as lambda to a general form

ex: allbits -> mask(lambda (x) -> (x == mask))
