### ISSUE TITLE
Learning Rust and WASM starting with Ruby?

### ISSUE THREAD

**Issue by philiprhoades** [artichoke/artichoke#1129]
People,

I have a general interest in Rust and WASM but am already a little familiar with Ruby - can I learn the basics of generating WASM with some simple but useful Ruby apps before moving on to Rust with its steeper learning curve?

Thanks,

Phil.

**Comment by lopopolo** [comment]
Hi @philiprhoades :wave: 

I think a good place to start will be the [artichoke/playground](https://github.com/artichoke/playground) repository.

Getting this building will get you an artichoke interpreter ready for the web.

The playground has some TypeScript glue that lets you invoke Artichoke from the browser.

Let me know if this sets you on the right track.

**Comment by lopopolo** [comment]
@philiprhoades I hope I've helped you get started. I'm going to close this issue. Feel free to reopen if there's anything else I can do to help.

**Comment by philiprhoades** [comment]
Yes, thanks for that!

**Comment by philiprhoades** [comment]
Sorry, I am very short of time with some life dramas going on and have only just got back to this - I will check it out now!

Thanks,

Phil.
