### ISSUE TITLE
Implement ENV object in Rust

### ISSUE THREAD

**Issue by lopopolo** [artichoke/artichoke#113]
[`ENV` is currently a stub](https://github.com/artichoke/artichoke/blob/60fe1be8d92660185909ea26a7ce633af5844224/artichoke-backend/src/extn/core/env.rb).

To support both `wasm32` and embedded builds, we should implement ENV with multiple backends:

- `std::env`
- `HashMap`

For an example of a similar component implemented in Rust with support for multiple backends, see [`Regexp`](https://github.com/artichoke/artichoke/blob/60fe1be8d92660185909ea26a7ce633af5844224/artichoke-backend/src/extn/core/regexp/mod.rs#L129-L132).

Expose methods on `State` to toggle the `ENV` backend.

**Comment by cdeler** [comment]
May I take this one?

**Comment by lopopolo** [comment]
Absolutely, it's all yours @cdeler. 💎

**Comment by lopopolo** [comment]
To support the in-memory backend, we my want to expose manipulating the interpreter environment as a trait on the interpreter, similar to `Warn`.

**Comment by lopopolo** [comment]
@cdeler I just realized the `ENV` API is fairly large. I don't think it is necessary to complete the [entire `ENV` API](https://ruby-doc.org/core-2.5.0/ENV.html) in one PR. Maybe focus on `ENV::[]` and `ENV::[]=` first since that is the part the glues together Rust and Ruby.

I had a peek at your branch and I think it is looking pretty good. 🙏 

Looking at the API, I think the only pieces we must implement in Rust are `ENV::[]`, `ENV::[]=`, `ENV::delete` and `ENV::to_h`. These four APIs would allow the rest to be implemented in Ruby.

**Comment by cdeler** [comment]
@lopopolo I've done with `ENV::[]` and `ENV::[]=`

I think `ENV::delete` could be emulated through `ENV::[]=nil`

I should add `ENV::to_h` or create PR?

**Comment by cdeler** [comment]
@lopopolo The diff for `ENV::[]` and `ENV::[]=` is [here](https://github.com/artichoke/artichoke/compare/master...cdeler:%23113_ENV_implementation?expand=1).

**Comment by lopopolo** [comment]
@cdeler we can add the `HashMap` backend as an add on in a subsequent PR. We'll just keep this ticket open until the `ENV` implementation is complete.

I probably won't have time to review your PR until the weekend. If you'd like to add `ENV::to_h` before then, that sounds good. If you'd prefer to push what you have, that works too. 😄 💎

**Comment by cdeler** [comment]
@lopopolo I've implemented 2 backends `EnvHashMapBackend` and `EnvStdBackend`, and `to_h` method.

But I cannot figure out how can I make it configurable (i.e. now we have to recompile `mod env`)

**Comment by lopopolo** [comment]
@cdeler that’s excellent! Could you submit a PR? I’ll aim to leave some feedback by 12p PDT on Saturday.

My strategy for getting this PR merged will be to leave feedback, file follow up tickets, and try to get things merged without too much friction :smile:

**Comment by cdeler** [comment]
@lopopolo what should I do to continue with this issue? Take the next one related to ENV?

**Comment by lopopolo** [comment]
@cdeler would you like to take GH-156?

**Comment by lopopolo** [comment]
This implementation is done so long as the missing `Hash` methods are implemented elsewhere in `extn`.

Thanks @cdeler!
