### ISSUE TITLE
Is artichoke useful in a production environment?

### ISSUE THREAD

**Issue by ZhangHanDong** [artichoke/artichoke#1251]
Hello, Ryan, is artichoke useful in a production environment?   Stripe ?

**Comment by lopopolo** [comment]
Hi Alex 👋 As far as I am aware, Artichoke is not used in a production setting. Artichoke has no use at Stripe. The software should be considered alpha quality.

What are you really trying to ask? Are you interested in using Artichoke in your own work? How can I help?

---
你好HanDong👋，如果你愿意，我们可以用中文交流😄。据我所知，Artichoke目前没有被用于生产环境，Stripe也没有采用Artichoke。Artichoke现在还处于发布前的状态。

你问这个问题是为什么呀？你是不是对在自己工作中使用Artichoke感兴趣呢？我可以怎样帮助你呢？

**Comment by ZhangHanDong** [comment]
@lopopolo  你好，你中文不错啊，感谢。 我也是喜欢 Ruby 和 Rust 。我看您在 Stripe 工作，并且看该项目已经兼容 Ruby 2.6.3，所以想了解一下该项目有没有用于你们公司生产。我在调研 Rust 行业应用，想做一份报告。我想知道，您对这个项目的期望和目标是什么？您有推动它用于生产环境的打算吗？还是只是自己的兴趣来做这个项目呢？

---
_(Translated by @lopopolo)_

Hello, you're good at Chinese. thank you. I also like Ruby and Rust. I think you work in Stripe and see that the project is already compatible with Ruby 2.6.3, so I want to know if the project is used for your company's production. I'm studying the Rust industry application and want to make a report. I want to know what your expectations and goals are for this project. Do you have any plans to promote its use in the production environment? Or is it just your own interest to do this project?

**Comment by lopopolo** [comment]
🙇‍♂️ I have help with my Chinese 😉. For now, I have no plans to take Artichoke to production. In the long term, I'd like Artichoke to be a fully compatible alternative Ruby implementation that compiles to WebAssembly. I see applications for Artichoke as an embedded scripting language in either games or browser-based WebAssembly applications. Artichoke's modular design allows for sandboxing core types like `ENV` and `Regexp` to support this.

Thanks for your question. I hope I've answered it and will close this issue.

---
我有帮手帮我翻译中文😉。现在来讲，我还没有计划将Artichoke应用到生产中。长远来讲，我希望Artichoke可以成为一个完全兼容的，可以在WebAssembly上编译的Ruby软件。我认为Artichoke可以被应用于游戏或者基于浏览器的WebAssembly应用的嵌入式脚本。Artichoke的模块化设计可以让用户隔离出像'ENV'和'Regexp'这样的API来实现这个目标。

谢谢你的留言，希望我已经解答了你的问题。

**Comment by ZhangHanDong** [comment]
@lopopolo 感谢解答。祝愿 Artichoke 能达成目标。我也会看这个项目来学习，后续有问题再请教您。

---
_(Translated by @lopopolo)_

Thank you for your answer. May Artichoke achieve its goal. I'll also look at this project to learn. I'll ask you later if you have any questions.
