### ISSUE TITLE
Some thoughts on the goals of the project

### ISSUE THREAD

**Issue by eregon** [artichoke/artichoke#133]
Hello there, I've been reading a bit about Artichoke and issues recently, and was wondering what was the motivation for a new implementation of Ruby.

Even though there is a great list of goals in the README, I'm not sure what each means or how they improve over the existing Ruby implementations (maybe it's just that the combination of all these goals improves over individual implementations?).
So what I'm looking for is the motivation behind this project and how it improves upon existing implementations.

What kind of deployments do you imagine? Ruby on Rails servers, embedded, others? How would those improve over the current implementations?

I couldn't find an explanation about the reason of using Rust as the implementation language (I don't know much about Rust), that could provide some interesting insights.

- [True parallelism with no GIL](https://github.com/artichoke/artichoke/milestone/4).

This is something that JRuby, TruffleRuby and Rubinius already have for Ruby code.

Do you mean this as a performance goal? What's the vision regarding performance of Artichoke? Do you think it would become faster than MRI, how?

- [Optional multi-threading](https://github.com/artichoke/artichoke/milestone/4).

What do you mean by optional multi-threading? Having a flag to disallow multi-threading?

- [Deterministic garbage collection](https://github.com/artichoke/artichoke/milestone/5).

What are the advantages of deterministic GC in the context of Ruby? Lower pause times?

In general, I think the throughput of reference counting is often slower than a well-tuned GC.
Deterministic garbage collection is probably quite challenging for MRI C extensions, given the model of marking functions in MRI.

- Single binary distribution (all Ruby sources from core and stdlib are
  embedded in `artichoke` executable).

MRuby already supports this, but it's a (small) subset of Ruby.
That's nice, do you plan to extend that to application code as well?
It might difficult to keep when reusing libraries such as zlib or libssl or gem's C extensions (they'd need to be statically linked I guess).

- [WebAssembly build target](https://github.com/artichoke/artichoke/milestone/6). Partially supported with the wasm32-unknown-emscripten target on the
  [playground](https://artichoke.github.io/artichoke/).

MRuby can already supports this as well, but it's a (small) subset of Ruby.
Is the idea to do client-side Ruby (instead of JavaScript)?
Or to make execution safer by running on top a of Wasm VM?

- [MRI](https://github.com/ruby/ruby)-compatible [C API](https://github.com/artichoke/artichoke/milestone/7).

The MRI C API enforces a lot of constrains on how native arrays and strings are represented. That might be quite tricky to deal with, performance-wise and compatibility-wise.

- [mruby](https://github.com/mruby/mruby)-compatible [C API (all 311 `MRB_API` functions)](https://github.com/artichoke/artichoke/milestone/7).

Is this because currently Artichoke is using MRuby as a backend and so it's easy?

How much of MRuby does Artichoke reuse? Re-implementing everything is a huge amount of work, so it sounds more feasible to me from experience to not reinvent the wheel for core classes, stdlibs, etc.

- [Emoji identifiers (classes, modules, methods, variables) 💪](https://github.com/artichoke/artichoke/milestone/8).

Doesn't MRI already support that?

- [Optional Standard Library](https://github.com/artichoke/artichoke/milestone/9).

Similar to MRuby, for embedded purposes?

- [Native Rust extensions exposed via `require` of virtual files](https://github.com/artichoke/artichoke/milestone/10).

Is that a new kind of native extensions?

- [Filesystem access is either via the system or via an in-memory virtual filesystem](https://github.com/artichoke/artichoke/milestone/11).

For embedding?

**Comment by lopopolo** [comment]
Hi @eregon. It might be helpful to provide a bit of context around the origin of Artichoke.

Artichoke originated as a replacement for the [mrusty](https://github.com/anima-engine/mrusty) crate in [rube](https://github.com/lopopolo/rube). One of rube's goals was to execute untrusted Ruby in the context of a webserver (or something similar like a game engine). This origin is where the motivation for:

- single static distribution
- virtual filesystem
- Rust native extensions
- optional standard library
- optional multi-threading (Artichoke currently offers a synchronous single-threaded implementation of `Thread` and `Mutex`)

For performance:

- Removing the GIL sounded fun. Other than that I haven't given it much thought.
- Artichoke plans to make use of Rust crates wherever possible and my hypothesis is that this will increase performance. For example, the [hybrid Regexp implementation](https://github.com/artichoke/artichoke/issues/57) using a Rust fast path is up to 10 times faster than MRI.

For GC:

- CactusRef is an experiment and seemed to unblock implementing a Rust VM more quickly.

Another goal is to provide a bed for experimentation that can potentially lead to upstreaming in MRI. This goal influences:

- The choice of Rust as an implementation language. Rust interops with C nicely.
- The desire for an [MRI-based backend](https://github.com/artichoke/artichoke/labels/B-MRI).
- Rust seems easier to experiment with a new VM than C.

The C API targets come from a desire for compatibility and adoption. I imagine they might make upstreaming easier.

For Wasm, I intend to make a full Ruby interpreter runnable anywhere Wasm is supported, e.g. the Web and Node.js.

I did not know MRI supported emoji identifiers. Thanks for the heads up.

```
[2.6.3] > 💎 = 'Ruby'
=> "Ruby"
[2.6.3] > 💎
=> "Ruby"
```

@eregon does this help to clarify things a bit? Thanks for asking this question and forcing me to think hard about the value that Artichoke brings to the Ruby community.

If you think this sounds reasonable, I'll work on pulling this together into the README with a PR. Would I be able to ask for your review?

**Comment by eregon** [comment]
Thank you for the insights, those explain quite well the motivation.
The PR looks good and I like the new README which is more specific about the vision.

> Another goal is to provide a bed for experimentation that can potentially lead to upstreaming in MRI. 

If you want to pursue this, I think it would be useful to ask relatively early on if MRI would consider adding Rust code in their codebase.

---

It's interesting for me, as I work on TruffleRuby and GraalVM, that some goals are fairly similar, but I'm sure the details will differ quite a bit.

For instance, GraalVM aims to provide [safe execution and embedding](https://www.graalvm.org/sdk/javadoc/org/graalvm/polyglot/Context.Builder.html), including a virtual filesystem, and managed execution of C code.
The virtual filesystem is not yet fully used in TruffleRuby, and one of the challenges there is to map the Ruby IO APIs which exposes raw file descriptors to operations of the virtual filesystem. And then to fully virtualize, sockets, pipes, etc, should also be handled to run more Ruby code in that mode.

Similarly, GraalVM has its own automaton-based and JIT'ed [regexp engine](https://github.com/oracle/graal/tree/master/regex) that supports most regular expressions but not everything, with a fallback on Joni for the unsupported features. It's not used yet in TruffleRuby but experiments are promising.

Finally, GraalVM can also [execute Rust code](https://www.graalvm.org/docs/reference-manual/languages/llvm/), which might make it possible to e.g., run Artichoke on top of GraalVM/TruffleRuby or Rust-Ruby native extensions in TruffleRuby.

**Comment by lopopolo** [comment]
Thank you @eregon. The feedback you've provided in this ticket has been super valuable.

I've filed GH-143 to reach out to the MRI folks about the possibility of upstreaming parts of Artichoke. The component I'm most interested in contributing is the `Regexp` and `MatchData` implementation.

I'm glad the new README addresses your questions about goals and motivation. Thanks for pushing Artichoke to be better. 💎
