### ISSUE TITLE
`airb` does not handle multiline input

### ISSUE THREAD

**Issue by stuarth** [artichoke/artichoke#1358]
`airb` does not currently handle multiline inputs correctly when it's entered line by line. To reproduce

```
>>> def foo
A fatal parsing error occurred
```

The same, in `irb`
```
irb(main):001:0> def foo
irb(main):002:1>
```

Note that pasting a multiline block _does_ work in `airb`
```
>>> def foo
  2
end
=> :foo
```

**Comment by lopopolo** [comment]
This ticket was filed as a followup to #1356.

**Comment by lopopolo** [comment]
The relevant code for handling incomplete parser state is here: https://github.com/artichoke/artichoke/blob/d2efb3aaa81bf12e0d29ee3edcc9fa9e100c5cae/src/parser.rs.

I think this probably regressed with the mruby 3 upgrade: https://github.com/artichoke/artichoke/pull/1125.

**Comment by stuarth** [comment]
@lopopolo happy to grab, this, but could use a bit of guidance if you have it. Specifically, we're falling into this branch

https://github.com/artichoke/artichoke/blob/d2efb3aaa81bf12e0d29ee3edcc9fa9e100c5cae/src/parser.rs#L142

and `error_buffer`

```rust
&parser.error_buffer = [
    mrb_parser_message {
        lineno: 0,
        column: 0,
        message: 0x0000000000000000,
    },
    mrb_parser_message {
        lineno: 0,
        column: 0,
        message: 0x0000000000000000,
    },
    mrb_parser_message {
        lineno: 0,
        column: 0,
        message: 0x0000000000000000,
    },
    mrb_parser_message {
        lineno: 0,
        column: 0,
        message: 0x0000000000000000,
    },
    mrb_parser_message {
        lineno: 0,
        column: 0,
        message: 0x0000000000000000,
    },
    mrb_parser_message {
        lineno: 0,
        column: 0,
        message: 0x0000000000000000,
    },
    mrb_parser_message {
        lineno: 0,
        column: 0,
        message: 0x0000000000000000,
    },
    mrb_parser_message {
        lineno: 0,
        column: 0,
        message: 0x0000000000000000,
    },
    mrb_parser_message {
        lineno: 0,
        column: 0,
        message: 0x0000000000000000,
    },
    mrb_parser_message {
        lineno: 0,
        column: 0,
        message: 0x0000000000000000,
    },
]
```

Not sure what to make about everything being 0'ed out. Any thoughts?

**Comment by lopopolo** [comment]
> Not sure what to make about everything being 0'ed out. Any thoughts?

`parser.error_buffer` is a fixed array field in an `mrb_parser_state`. When everything is zero, this memory is uninitialized and zeroed.

https://github.com/artichoke/artichoke/blob/858b686ed93fa3b23b4e65d0dc64d1ea6e591cb6/artichoke-backend/vendor/mruby/include/mruby/compile.h#L161

Let me dig and see what `nerr` means now.

**Comment by lopopolo** [comment]
This function from mruby's `mirb`:

https://github.com/artichoke/artichoke/blob/858b686ed93fa3b23b4e65d0dc64d1ea6e591cb6/artichoke-backend/vendor/mruby/mrbgems/mruby-bin-mirb/tools/mirb/mirb.c#L136-L231

is meant to correspond with this one:

https://github.com/artichoke/artichoke/blob/858b686ed93fa3b23b4e65d0dc64d1ea6e591cb6/src/parser.rs#L46-L57

Let me know if this leads you down a productive path @stuarth.
