### ISSUE TITLE
Fix build warnings for mruby-sys

### ISSUE THREAD

**Issue by lopopolo** [artichoke/artichoke#137]
```console
$ cargo clippy --all-targets --all-features
warning: couldn't execute `llvm-config --prefix` (error: No such file or directory (os error 2))
warning: set the LLVM_CONFIG_PATH environment variable to a valid `llvm-config` executable
    Finished dev [unoptimized + debuginfo] target(s) in 0.50s
```

I think this was caused by switching the mruby build toolchain to clang.

https://github.com/artichoke/artichoke/blob/ff426131ca32ead78a46684a6b50b17f4e2c26ac/mruby-sys/debug_build_config.rb#L10

I'm getting these warnings on macOS 10.14.6 with this clang

```console
$ clang --version
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by abelsromero** [comment]
Als `cargo build`, `cargo test`, etc. fail on Linux if clang is not installed.
This should probably be explained in the toolchain guide: https://github.com/artichoke/artichoke/blob/master/CONTRIBUTING.md#rust-toolchain

**Comment by lopopolo** [comment]
Building `mruby-sys` currently depends on a `clang` toolchain being installed + `bintools` + `yacc` + `gperf` + `ruby`.

https://github.com/artichoke/artichoke/blob/6ad780b1a9899155bc7fe9a71a5b8eb3d16acc2f/.circleci/config.yml#L48-L61

I have ideas on how we can modify the `mruby-sys` build to depend on the `cc` crate. This would still depend on `yacc` for generating the parser C source and maybe `gperf`.

See GH-145.

**Comment by lopopolo** [comment]
See https://github.com/artichoke/artichoke-ci/issues/4

**Comment by lopopolo** [comment]
These warnings come from `clang-sys` which is pulled in by `bindgen`. These warnings will go away once `bindgen` releases a version that depends on `clang-sys` 1.0.0.

https://github.com/rust-lang/rust-bindgen/pull/1826#issue-448653594

**Comment by lopopolo** [comment]
Fixed by https://github.com/artichoke/artichoke/pull/804
