### ISSUE TITLE
Investigate using the oxidised parser from rubyfmt

### ISSUE THREAD

**Issue by lopopolo** [artichoke/artichoke#139]
rubyfmt has an in progress PR to implement a pure Rust parser for arbitrary Ruby versions.

https://github.com/penelopezone/rubyfmt/pull/147

Investigate the feasibility of incorporating this parser into Artichoke.

This would implement https://github.com/artichoke/artichoke/issues/83.

**Comment by cdeler** [comment]
I'm sorry for that, but why cant you use tree-sitter ?
https://github.com/tree-sitter/tree-sitter

It has been written on `Rust`, without 3p, has ruby support (https://github.com/tree-sitter/tree-sitter-ruby)

**Comment by lopopolo** [comment]
Interesting. I wasn't aware of [tree-sitter](https://github.com/tree-sitter/tree-sitter). Thanks @cdeler 🚀 I've filed GH-144 to investigate using tree-sitter.

**Comment by lopopolo** [comment]
> It has been written on `Rust`, without 3p, has ruby support (https://github.com/tree-sitter/tree-sitter-ruby)

@cdeler out of curiousity, what does _3p_ mean in this context?

**Comment by cdeler** [comment]
@lopopolo Third Parties

**Comment by lopopolo** [comment]
This is no longer necessary since the `lib-ruby-parser` crate exists. Additionally, there is an effort in MRI to create a portable parser that all Ruby implementations can share. See:

- https://github.com/artichoke/artichoke/issues/923
- https://github.com/Shopify/yarp
