### ISSUE TITLE
Add an interpreter-global hasher

### ISSUE THREAD

**Issue by lopopolo** [artichoke/artichoke#1404]
To facilitate APIs like `String#hash`, it would help to dangle a [`BuildHasher`] like [`RandomState`] off of the interpreter and expose it with a trait in `artichoke-core`. 

[`BuildHasher`]: https://doc.rust-lang.org/std/hash/trait.BuildHasher.html
[`RandomState`]: https://doc.rust-lang.org/std/collections/hash_map/struct.RandomState.html

I imagine a trait like:

```rust
// This trait is identical to `BuildHasher`.
pub trait Hash: core::hash::BuildHasher {}
```

To implement this trait in `artichoke-backend`, add a `RandomState` to the interpreter state:

https://github.com/artichoke/artichoke/blob/fdc7bb6ef8d2023abaa672040efe902f0ccea030/artichoke-backend/src/state/mod.rs#L24-L35

and implement the trait in a source file at `artichoke-backend/src/hash.rs`, like this example for `Warn`:

https://github.com/artichoke/artichoke/blob/fdc7bb6ef8d2023abaa672040efe902f0ccea030/artichoke-backend/src/warn.rs#L14-L41

This blocks #1222.

**Comment by masonforest** [comment]
Hey @lopopolo  and team,

Thanks for all your great work so far!

I’ve started on this [here](https://github.com/artichoke/artichoke/compare/trunk...masonforest:add-global-hasher?expand=1) but I’ve got some questions:

1. I tried extending `Hash` from `core::hash::BuildHasher` as suggested but `BuildHasher#build_hash` takes `&self` as its first argument and I think we need it to take `&mut self` to get `state` out of self so I built my own trait instead. Does this make sense?

2. Is it alright that `State` can only take a `RandomState` or do we want to make this more generic than that?


Also some neat things I learned while investigating that you may already know but thought I’d share:

1. Ruby MRI 1.8.7's string hashing algorithm is actually called One-At-A-Time Hasher and it's been implemented in rust [here](https://github.com/tmmcguire/hashers/blob/master/src/jenkins/mod.rs#L33). It also looks like MRI 1.8.7 can be configured to use ElfHash.

2. It looks like the latest MRI [uses SipHash13](https://github.com/ruby/ruby/blob/cb4e2cb55a59833fc4f1f6db2f3082d1ffcafc80/random.c#L1668) which is what `RandomState` uses. Nice!

**Comment by lopopolo** [comment]
Thanks @masonforest your branch is looking pretty good.

A couple of bits of feedback and I think this is good to submit as a PR:

- Good eye on needing to take `&mut self` to destructure the `state`.
- `artichoke-core` supports building in `no_std` mode, so I think I'd like the build hasher to be an associated type that is generically bound by `core::hash::BuildHasher`. Then `artichoke-backend` would declare its impl with the associated type of `RandomState`.
- Let's return `Result<&Self::BuildHasher, Self::Error>` to avoid an unnecessary clone since `BuildHasher::build_hasher` only requires `&self`.

> Also some neat things I learned while investigating that you may already know but thought I’d share:

😄 you might want to take a look at:

- https://github.com/artichoke/artichoke/pull/1450
- https://twitter.com/artichokeruby/status/1444089207547330562

and:

https://github.com/artichoke/artichoke/blob/ba6158c1bd917cbdfcc30872990c176230a83f9f/spinoso-string/src/ffi/mruby.rs#L5-L29
