### ISSUE TITLE
Building mruby-sys and rust-onig without emscripten requires trunk clang

### ISSUE THREAD

**Issue by lopopolo** [artichoke/artichoke#149]
mruby-sys and rust-onig use computed gotos.

Building with clang instead of emscripten for the wasm32 targets requires a clang with this fix: https://bugs.llvm.org/show_bug.cgi?id=42498

**Comment by lopopolo** [comment]
Something like this will install trunk clang in CircleCI:

```yaml
      - run:
          # needed for cc crate in build.rs
          name: Install LLVM toolchain
          command: |
            sudo apt-get install software-properties-common
            wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
            sudo apt-add-repository 'deb http://apt.llvm.org/buster/ llvm-toolchain-buster main'
            sudo apt-get update
            sudo apt-get install -y clang lld
            clang --version
```

**Comment by lopopolo** [comment]
clang 10 snapshots are not available via the apt repository.

**Comment by lopopolo** [comment]
The Dockerfile for the base image in https://github.com/artichoke/artichoke-ci bundles snapshot clang-9.

**Comment by singpolyma-shopify** [comment]
If you use:

```diff
diff --git a/src/regexec.c b/src/regexec.c
index fa61839..94aa465 100644
--- a/src/regexec.c
+++ b/src/regexec.c
@@ -2338,9 +2338,11 @@ typedef struct {
 } posix_regmatch_t;
 
 
+#if 0
 #ifdef __GNUC__
 #define USE_THREADED_CODE
 #endif
+#endif
 
 #ifdef USE_THREADED_CODE
 ```

Then the computed gotos are not needed anymore and it will build with any llvm-8 for wasm32-unknown-unknown

**Comment by singpolyma-shopify** [comment]
[build.sh.txt](https://github.com/artichoke/artichoke/files/3493997/build.sh.txt)

That should reproduce my current state, including the mis-linked airb.wasm file

**Comment by lopopolo** [comment]
Thanks for the build steps @singpolyma-shopify. I've made some progress on this: https://github.com/artichoke/artichoke/pull/172.

Still failing at link type, but new and exciting linker errors. If you could help me sort these out I'd be 🙏

**Comment by lopopolo** [comment]
https://github.com/kkos/oniguruma/pull/150 added a `ONIG_DISABLE_DIRECT_THREADING` macro to oniguruma which can be used to disable computed gotos in the match engine. Defining this flag enables building a oniguruma for the wasm32-unknown-unknown target with clang-8.

https://github.com/rust-onig/rust-onig/pull/115 pulls this oniguruma patch into rust-onig and adds support for wasm targets to the onig_sys `build.rs`.

The `MRB_DISABLE_DIRECT_THREADING` macro disables computed gotos when building mruby. An in-progress PR defines this macro for wasm targets https://github.com/artichoke/artichoke/pull/172/commits/710515cc2af3ce3da6669df3a847879f54d6c4d5.

**Comment by lopopolo** [comment]
This has been fixed for a while now. The playground builds with LLVM 11.
