### ISSUE TITLE
Implement `artichoke_backend::module::Registry::shrink_to`

### ISSUE THREAD

**Issue by lopopolo** [artichoke/artichoke#1503]
`module::Registry` in the `artichoke-backend` crate implements several APIs for manipulating the underlying allocations such as `module::Registry::reserve` and `module::Registry::shrink_to_fit`.

Artichoke depends on the most recent stable Rust compiler and Rust 1.56.0 stabilized [`HashMap::shrink_to`]. `module::Registry` is built on `HashMap`, so we can add a corresponding `module::Registry::shrink_to` API.

The code we'll want to add should be placed below the definition of `module::Registry::shrink_to_fit`:

https://github.com/artichoke/artichoke/blob/11ba967aee3d3527482c12658bcf70edd62055cb/artichoke-backend/src/module/registry.rs#L225-L227

See a similar PR in [artichoke/intaglio] for inspiration around how to structure the doc comments:

- https://github.com/artichoke/intaglio/pull/107
- https://github.com/artichoke/intaglio/commit/592b41622a2b136ce3d106b2ebb15bfe28a2642b

## Similar Tickets

If you're interested in working on this, you might also consider taking:

- https://github.com/artichoke/artichoke/issues/1502

[`HashMap::shrink_to`]: https://doc.rust-lang.org/stable/std/collections/hash_map/struct.HashMap.html#method.shrink_to
[artichoke/intaglio]: https://github.com/artichoke/intaglio

**Comment by kolharsam** [comment]
@lopopolo This is an issue that I'd like to take up. Is it up for grabs?

**Comment by lopopolo** [comment]
@kolharsam go for it.

**Comment by kolharsam** [comment]
@lopopolo The difference between this issue and #1502 is not apparent to me. Could you provide me with some context for the same?

**Comment by lopopolo** [comment]
The class registry and module registry are two implementations of the same datastructure with different value types in the inner hashmap.

The change that needs to be made to each is the same. These two data structures live in different source files.

These are the main differences between them:

## Spec type

https://github.com/artichoke/artichoke/blob/11ba967aee3d3527482c12658bcf70edd62055cb/artichoke-backend/src/module/registry.rs#L29

https://github.com/artichoke/artichoke/blob/11ba967aee3d3527482c12658bcf70edd62055cb/artichoke-backend/src/class/registry.rs#L29

## Iterator over specs

https://github.com/artichoke/artichoke/blob/11ba967aee3d3527482c12658bcf70edd62055cb/artichoke-backend/src/module/registry.rs#L137-L142

https://github.com/artichoke/artichoke/blob/11ba967aee3d3527482c12658bcf70edd62055cb/artichoke-backend/src/class/registry.rs#L137-L142

**Comment by lopopolo** [comment]
Apologies for making it confusing splitting these tickets in two.
