### ISSUE TITLE
Implement the rest of the ENV API in Ruby

### ISSUE THREAD

**Issue by lopopolo** [artichoke/artichoke#156]
Follow up to GH-148.

GH-148 implements `ENV::[]`, `ENV::[]=` and `ENV::to_h` in Rust. The [rest of the API](https://ruby-doc.org/core-2.6.3/ENV.html) can be implemented in Ruby in terms of these primitives.

**Comment by cdeler** [comment]
@lopopolo May I take this one?

**Comment by lopopolo** [comment]
@cdeler yes it's all yours.

**Comment by cdeler** [comment]
@lopopolo If it's possible, could you assign the issue to me? It could help me to track it.

**Comment by lopopolo** [comment]
Done.

**Comment by cdeler** [comment]
@lopopolo Please could you pay an attention to my local branch? ([link](https://github.com/artichoke/artichoke/compare/master...cdeler:%23156-implement-rest-ENV-API-in-ruby?expand=1))

I'm not familiar with ruby, am I doing well?

**Comment by lopopolo** [comment]
Hi @cdeler this is looking really good!

The goal is to implemented the [`ENV` API for Ruby 2.6.3](https://ruby-doc.org/core-2.6.3/ENV.html).

As with the last PR, I'd like to keep this incremental. Maybe address the feedback below and submit a PR with your progress so far? Thanks again for your help 💎 

## API Coverage

- [x] ::[]
- [x] ::[]=
- [x] ::assoc
- [x] ::clear
- [x] ::delete
- [ ] ::delete_if
- [ ] ::each
- [ ] ::each_key
- [ ] ::each_pair
- [ ] ::each_value
- [x] ::empty?
- [ ] ::fetch
- [ ] ::filter
- [ ] ::filter!
- [x] ::has_key?
- [x] ::has_value?
- [x] ::include?
- [ ] ::index
- [ ] ::inspect
- [ ] ::invert
- [ ] ::keep_if
- [x] ::key
- [ ] ::key?
- [ ] ::keys
- [x] ::length
- [ ] ::member?
- [ ] ::rassoc
- [x] ::rehash
- [ ] ::reject
- [ ] ::reject!
- [ ] ::replace
- [ ] ::select
- [ ] ::select!
- [x] ::shift
- [x] ::size
- [x] ::slice
- [ ] ::store
- [x] ::to_a
- [x] ::to_h
- [x] ::to_hash
- [x] ::to_s
- [x] ::update
- [x] ::value?
- [x] ::values
- [x] ::values_at

## Review

The linter probably won't pick up on these, but indents should be two spaces. I prefer to define methods alphabetically to [line up with the docs](https://ruby-doc.org/core-2.6.3/ENV.html).

An explicit `self` receiver is not needed in most cases (really only for calling `self[]` and `self[]=`). For example, `self.to_h` can be written as `to_h`. Running the linter with `yarn lint` will auto fix errors like this. Running the linter requires a recent Node, Yarn, and Ruby.

I prefer to short circuit and use modifier if or guard clauses to simplify the control flow of a method. For example, I'd change `ENV::delete` to:

```ruby
def delete(name)
  value = self[name]
  return nil if value.nil?

  self[name] = nil
  yield name if block_given?

  value
end
```

`ENV::delete_if` returns an enumerator if no block is given. It can be implemented like this:

```ruby
def delete_if
  return to_enum(:delete_if) unless block_given?

  each do |key, value|
    delete(key) if yield key, value
  end
  to_h
end
```

All blocks in Ruby implicitly return the result of their last expression. Explicit return like in `ENV::empty?` is not necessary.

In `ENV::shift`, you can destructure the pair with:

```ruby
name, _value = envs.shift
```

**Comment by lopopolo** [comment]
Hi @cdeler checking in. Are you still working on this issue?

**Comment by cdeler** [comment]
Hello @lopopolo

I'm on vacation (without notebook) now. I want to continue working on the issue, but you can take it back, if it blocks you

I have the branch with changes pushed to my fork. But your remarks haven't been fixed yet.

**Comment by lopopolo** [comment]
Oh no! I don't mean to disrupt your vacation. I'm sorry.

I'm not blocked. We can pick this up when you get back.

**Comment by cdeler** [comment]
So lets continue :-)

**Comment by cdeler** [comment]
@lopopolo Am I right that all `ENV` methods are implemented?

**Comment by lopopolo** [comment]
So close! It looks like we're missing `ENV::reject!`.

@cdeler I want to let you have the satisfaction of getting this API completely spec-compliant if you want to. I've filed GH-268 to follow up.

After `ENV::reject!` gets added, we can close this ticket.
