### ISSUE TITLE
Say something about speed / benchmark in the readme

### ISSUE THREAD

**Issue by grosser** [artichoke/artichoke#1638]
Would be nice to know what I can expect speed, memory, and startup-time wise when using artichoke.
Even if it's temporary / slow, knowing if it's 1/10/100x slower would help me decide if it makes sense to try building projects with it.

something like:
```
# Benchmarks
Atm artichoke is not optimized for speed. For basic tasks you can expected 5x slower, 10x more memory and 100x boot time compared to cruby.
```

**Comment by lopopolo** [comment]
Hi @grosser. Without addressing the snippet you provided, Artichoke makes no guarantees around its performance.

I'm not sure what you're trying to build, but at this point the only guidance I can give is to try things out yourself.

Pre-built artifacts are available on all major platforms and are published nightly:

- https://github.com/artichoke/nightly/releases/latest

Nightly Docker images are published as well:

- https://github.com/artichoke/docker-artichoke-nightly

I'm not interested in accepting changes to the README like you've suggested here.

**Comment by grosser** [comment]
Saying "Artichoke makes no guarantees around its performance." would be a
start.
Maybe listing things it's good/bad at and giving a general "for xyz example
workload it performs like xyz",
or linking to a issue/doc about what performance challenges are open/know
to send people that care about performance into the right direction.
