### ISSUE TITLE
`String::make_binary` should clone instead of mutate; rename to `String::to_binary`

### ISSUE THREAD

**Issue by lopopolo** [artichoke/artichoke#1720]
Yes, I'm hoping this is the issue I was thinking of:

```irb
irb(main):001:0> a = "a"
=> "a"
irb(main):002:0> b = a.b
=> "a"
irb(main):003:0> a.object_id
=> 18440
irb(main):004:0> b.object_id
=> 25120
```

Specifically: https://ruby-doc.org/core-3.1.1/String.html#method-i-b <-- Says it'll return a copied string, where as this Rust implementation is just changing the encoding still. If that still feels like the implementation isn't "correct", then I'll raise the issue!

_Originally posted by @b-n in https://github.com/artichoke/artichoke/pull/1678#r820242310_

Also make changes to the implementation of `String#b` in `artichoke-backend` to do a clone and make a newly allocated `Value`. Relevant code:

https://github.com/artichoke/artichoke/blob/f7067c2dc0a80339dce95cd99b5ad6c7a27a89d3/artichoke-backend/src/extn/core/string/trampoline.rs#L374-L379

**Comment by b-n** [comment]
@lopopolo So, I was just having a look at this one again for the funs. I missed the part in artichoke-backend where the value was being cloned - and thus technically artichoke-backend actually does give a different object_id (the same as a cruby).

I'm curious design of spinoso-*. I'm assuming it's to just abstract the implementations away the ruby primitives and isolate them some more. it makes me think about `make_binary` since it's technically valid, but it's just a little confusing with the idea that it should always be cloned and thus requires artichoke-backend to know that too. Thoughts?

**Comment by lopopolo** [comment]
@b-n I think I'd like the spinoso APIs to mirror MRI as closely as possible so the trampolines, which are backend specific, are as thin as possible.

This means `String::make_binary` is probably the wrong API. I think we actually want `String::to_binary(&self) -> Self` where this function would do the clone with the proper encoding set.

**Comment by lopopolo** [comment]
having `String::to_binary` rather than `String::clone` + `String::make_binary` also has some marginal perf benefits, since we directly construct the string we want rather than having to move between variants in `EncodedString`.

**Comment by b-n** [comment]
Yep, makes total sense! 

And on a slightly related subject, I assume some of the implementations in the trampoline for string (e.g. [byteslice](https://github.com/artichoke/artichoke/blob/trunk/artichoke-backend/src/extn/core/string/trampoline.rs#L397)) could also be moved to spinoso-string?

**Comment by lopopolo** [comment]
The code in `trampoline::byteslice` is actually the type of code I want to keep in the trampolines.

It is mostly marshaling polymorphic arguments from the VM into the raw slicing APIs on the `String` and then converting them back to VM `Value`s.

It looks big because of the comments, but basically anything that deals with `i64`, implicit conversions, or `Value` construction/alloc should live in the trampoline.

**Comment by b-n** [comment]
Huh, that's really clever, and also makes sense once again. In my head I now have this as keeping the dynamic rubyish vm things near the vm, and then the more primitive logic/management in spinoso[s]. Nice
