### ISSUE TITLE
`Regexp::escape` differs between MRI and Artichoke for meta characters

### ISSUE THREAD

**Issue by lopopolo** [artichoke/artichoke#1738]
## MRI

```console
$ irb
[3.1.1] > s = '\.+*?()|[]{}^$#&-~'
=> "\\.+*?()|[]{}^$#&-~"
[3.1.1] > puts Regexp.escape(s)
\\\.\+\*\?\(\)\|\[\]\{\}\^\$\#&\-~
=> nil
[3.1.1] >
```

## Artichoke

```console
$ cargo run --bin airb -q
artichoke 0.1.0-pre.0 (2022-03-11 revision 5352) [x86_64-apple-darwin]
[rustc 1.58.1 (db9d1b20b 2022-01-20) on x86_64-apple-darwin]
>>> s = '\.+*?()|[]{}^$#&-~'
=> "\\.+*?()|[]{}^$#&-~"
>>> puts Regexp.escape(s)
\\\.\+\*\?\(\)\|\[\]\{\}\^\$\#\&\-\~
=> nil
>>>
```

## Diff

```
M: \\\.\+\*\?\(\)\|\[\]\{\}\^\$\#&\-~
A: \\\.\+\*\?\(\)\|\[\]\{\}\^\$\#\&\-\~
```

It looks like Artichoke is adding an escape slash for `&` and `~` where MRI is not.

## Implicated Code

https://github.com/artichoke/artichoke/blob/15726cd327e519cee2dab9cc7fab717be265d8f6/artichoke-backend/src/extn/core/regexp/syntax.rs#L48-L63

**Comment by noraj** [comment]
I may be wrong but if the readme says artichoke targets cruby 2.6.3 shouldn't your compare with cruby 2.6.3 instead of 3.1.1?

**Comment by lopopolo** [comment]
In practice I don't keep MRI 2.6.3 installed on my machines. When I compare Artichoke to MRI, I use whatever the latest version I happen to have installed.
