### ISSUE TITLE
Implement Integer#size in Rust

### ISSUE THREAD

**Issue by lopopolo** [artichoke/artichoke#179]
One of the [patches we carry to mspec](https://github.com/artichoke/mspec/commit/9a9d3d0a2339a8cb3a0579d7cac6d76ce5870ab3) works around the lack of an `Integer#size` implementation.

This function is easily implemented in Rust using `artichoke_backend::types::Int` and [`mem::size_of`](https://doc.rust-lang.org/std/mem/fn.size_of.html).

https://github.com/artichoke/artichoke/blob/35adec79094c5406468225d377a22c6ca4fb7709/artichoke-backend/src/types.rs#L6-L10

**Comment by tkbky** [comment]
I would like to give this a try.
