### ISSUE TITLE
WASI-SDK or Emscripten as target?

### ISSUE THREAD

**Issue by glyh** [artichoke/artichoke#1812]
Here's an [issue](https://github.com/WebAssembly/wasi-sdk/issues/222) clarifying their difference. 

I don't know what you think about, but I personally think the first option is more portable.

**Comment by glyh** [comment]
Find a better place for discussion, closing this instead.

**Comment by lopopolo** [comment]
Linking https://github.com/artichoke/artichoke/issues/1633#issuecomment-1086683158.
