### ISSUE TITLE
`gh-pages` branch is huge, makes git clones slow

### ISSUE THREAD

**Issue by lopopolo** [artichoke/artichoke#1826]
The `gh-pages` branch in this repository is huge, which causes the repo to be ~500MB.

rustdoc includes generated sources which end up in `OUT_DIR` in the generated docs, despite them not being reachable from the generated HTML. These generated sources also include the full path into the target dir which makes it harder for git to dedup them.

Additionally, I'm not sure how valuable it is to keep history in the `gh-pages` branch since these are derived artifacts. The only reason they get pushed to `gh-pages` is for web hosting.

I think with the [`force_orphan: true`](https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-force-orphan-force_orphan) option to the gh-pages GitHub Action this repository uses, we can only keep one commit of history in the branch.

Additionally, something like this can prevent these large generated files from being committed to git in the first place:

```sh
find . -path '*/target/debug/build/*' | xargs rm -rf
```

## Investigation

Question from @cloudhead:

> btw do you know why the artichoke repo is so big?
> ```
> Receiving objects: 100% (1505757/1505757), 572.83 MiB | 4.47 MiB/s, done.
> ```
> took me quite a long time to clone

Per @b-n:

> looks like there were a bunch of 25mb files in the object history in this location in the past: > `src/chrono_tz/home/runner/work/artichoke/artichoke/target/debug/build/chrono-tz-3124697c7c2a7d2d/out/timezones.rs.html` (and since they were hashed they were added/changed a bunch of times)

For example: https://github.com/artichoke/artichoke/blob/gh-pages/src/chrono_tz/home/runner/work/artichoke/artichoke/target/debug/build/chrono-tz-b1ee743cc6ddd31d/out/timezones.rs.html <-- 24mb file

https://github.com/artichoke/artichoke/tree/cccb4e286945517c17b3f9b50e8bed41cca40c00/src/chrono_tz/home/runner/work/artichoke/artichoke/target/debug/build/chrono-tz-b1ee743cc6ddd31d/out

Thanks @cloudhead for reporting this on Discord and @b-n for investigating.

**Comment by lopopolo** [comment]
as of the current branch HEADs, a fresh clone pulls down 577MB and takes 1.5 minutes (on fast internet).

```console
$ git clone git@github.com:artichoke/artichoke.git
Cloning into 'artichoke'...
Host key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU
+--[ED25519 256]--+
|                 |
|     .           |
|      o          |
|     o o o  .    |
|     .B S oo     |
|     =+^ =...    |
|    oo#o@.o.     |
|    E+.&.=o      |
|    ooo.X=.      |
+----[SHA256]-----+
remote: Enumerating objects: 1522015, done.
remote: Counting objects: 100% (365821/365821), done.
remote: Compressing objects: 100% (34764/34764), done.
remote: Total 1522015 (delta 349861), reused 344818 (delta 329353), pack-reused 1156194
Receiving objects: 100% (1522015/1522015), 576.84 MiB | 11.88 MiB/s, done.
Resolving deltas: 100% (1426689/1426689), done.
Updating files: 100% (17864/17864), done.
```

**Comment by lopopolo** [comment]
yay! this worked! 10x reduction in `git clone` size, down to ~50MB.

## Before

```console
$ git clone git@github.com:artichoke/artichoke.git
Cloning into 'artichoke'...
Host key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU
+--[ED25519 256]--+
|                 |
|     .           |
|      o          |
|     o o o  .    |
|     .B S oo     |
|     =+^ =...    |
|    oo#o@.o.     |
|    E+.&.=o      |
|    ooo.X=.      |
+----[SHA256]-----+
remote: Enumerating objects: 1522015, done.
remote: Counting objects: 100% (365821/365821), done.
remote: Compressing objects: 100% (34764/34764), done.
remote: Total 1522015 (delta 349861), reused 344818 (delta 329353), pack-reused 1156194
Receiving objects: 100% (1522015/1522015), 576.84 MiB | 11.88 MiB/s, done.
Resolving deltas: 100% (1426689/1426689), done.
Updating files: 100% (17864/17864), done.
$ du -hs artichoke
774M    artichoke
```

## After

```console
$ git clone git@github.com:artichoke/artichoke.git artichoke-shrinked
Cloning into 'artichoke-shrinked'...
Host key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU
+--[ED25519 256]--+
|                 |
|     .           |
|      o          |
|     o o o  .    |
|     .B S oo     |
|     =+^ =...    |
|    oo#o@.o.     |
|    E+.&.=o      |
|    ooo.X=.      |
+----[SHA256]-----+
remote: Enumerating objects: 84876, done.
remote: Counting objects: 100% (23767/23767), done.
remote: Compressing objects: 100% (3043/3043), done.
remote: Total 84876 (delta 21250), reused 22886 (delta 20546), pack-reused 61109
Receiving objects: 100% (84876/84876), 53.20 MiB | 9.05 MiB/s, done.
Resolving deltas: 100% (54959/54959), done.
Updating files: 100% (17864/17864), done.
$ du -hs artichoke-shrinked
197M    artichoke-shrinked
```

**Comment by cloudhead** [comment]
Amazing!
