### ISSUE TITLE
Add a `tz-rs` backend to `spinoso-time`

### ISSUE THREAD

**Issue by lopopolo** [artichoke/artichoke#1833]
- https://github.com/x-hgg-x/tz-rs
- https://github.com/Kijewski/tzdb

`tz-rs` describes itself as:

> A pure Rust reimplementation of libc functions [localtime](https://en.cppreference.com/w/c/chrono/localtime), [gmtime](https://en.cppreference.com/w/c/chrono/gmtime) and [mktime](https://en.cppreference.com/w/c/chrono/mktime).
>
> This crate allows to convert between a [Unix timestamp](https://en.wikipedia.org/wiki/Unix_time) and a calendar time exprimed in the [proleptic gregorian calendar](https://en.wikipedia.org/wiki/Proleptic_Gregorian_calendar) with a provided time zone.
>
> Time zones are provided to the library with a [POSIX TZ string](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html) which can be read from the environment.

This is basically exactly what is needed to implement the `Time` core class.

`tz-rs` combined with `tzdb` should make a full `Time` implementation easier to achieve. There are no panicking APIs which should help too.

Once this is rolled out, consider removing the `chrono` backend, which would allow addressing:

https://github.com/artichoke/artichoke/blob/914bea3c8209ff9ac3299151aa220cdf384afc27/deny.toml#L6-L8

**Comment by b-n** [comment]
> This is basically exactly what is needed to implement the Time core class.

@lopopolo I'm a little confused,`Time` is already implement in artichoke backend from `spinoso-time`

Is this ticket about trying to replace the usage of `chrono` with `tz-rs` in order to remove `RUSTSEC-2020-0159` ?

**Comment by lopopolo** [comment]
Some spinoso crates implement the type multiple times with an identical API. For example, spinoso-array implements the `Array` data structure three times, each with identical APIs, with `Vec`, `SmallVec`, and `TinyVec` as the backing store: https://github.com/artichoke/artichoke/tree/78803b6b6e53bd11aabe7826c41fb3b089e5c3f3/spinoso-array/src/array.

Similarly, spinoso-env implements the `ENV` data structure twice: once with `std::env` and once with `HashMap`: https://github.com/artichoke/artichoke/tree/78803b6b6e53bd11aabe7826c41fb3b089e5c3f3/spinoso-env.

I've been referring to the multiple implementations as "backends" for the core class.

These backends are normally nestled in `spinoso_x::x::backend_dep::*`, so for example: `spinoso_array::array::tinyvec::TinyArray`.

The `chrono` backend for `Time` is located at `spinoso_time::time::chrono::`: https://github.com/artichoke/artichoke/tree/78803b6b6e53bd11aabe7826c41fb3b089e5c3f3/spinoso-time/src/time/chrono.

This ticket is asking for an additional implementation of `Time` in spinoso-time.

**Comment by b-n** [comment]
Aahhhh right. That's kinda clever! In which case this'll be a fun challenge. I'll give it a whirl!

**Comment by b-n** [comment]
@lopopolo Just a small FYI, I'm still stuck on a presentation, but the good news is that I give said presentation on thursday, and then I get my freetime/life back, and then this issue will be on the way!

**Comment by lopopolo** [comment]
@b-n all good, there's no rush here.
