### ISSUE TITLE
[Advice] Just know this rust ruby implementation, but, this name look's like not good.

### ISSUE THREAD

**Issue by zw963** [artichoke/artichoke#1843]
I consider any success language, must be a very pretty name. e.g. `ruby`, `rust`, `go` etc.

i consider it should at most 5~6 char too.

i consider artichoke as a name, it very bad for me. (at least for a Asian, English is not a mother tongue)

it too long, and hard to remember, even can't guess how to pronounce it.

anyway, just a device.

**Comment by lopopolo** [comment]
I do not consider this advice welcome or constructive. Artichoke and the entire project will not be changing its name.
