### ISSUE TITLE
Find (or create) a `strftime` implementation for `spinoso-time`

### ISSUE THREAD

**Issue by b-n** [artichoke/artichoke#1914]
Whilst integration `tz-rs` in #1902, I noticed that there was no pure rust `no-std` implementations of `strftime`.

Research:

- `chrono` - tightly coupled with `chrono` itself
- `time` - formatting feature requires `std`: https://docs.rs/time/0.3.11/time/
- `libc-strftime` - just a libc wrapper
- `time-format` - `strftime()` is just wrapping the C implementation

Options:

- Pick one of the above options
- We take inspiration from `tz-rs` and make `strftime-rs` :+1: :100:

**Comment by lopopolo** [comment]
As a heads up, the `time` crate is banned in Artichoke, so I don't consider it to be an option (happy to chat on Discord about this if you'd like):

- https://github.com/artichoke/artichoke/pull/858
 - https://github.com/artichoke/artichoke/blob/686419005da4689a45b0a8450b34a3cda1018874/deny.toml#L30-L32

Another options is to port the (relatively encapsulated) module from MRI to no-std + alloc Rust:

- https://github.com/ruby/ruby/blob/v3_1_2/strftime.c

**Comment by lopopolo** [comment]
> * We take inspiration from `tz-rs` and make `strftime-rs` 👍 💯

Let's try this. Sandbox repo with all the scaffolding is here: https://github.com/artichoke/strftime-ruby.

**Comment by lopopolo** [comment]
Once implemented, the formatter should be plugged in here:

https://github.com/artichoke/artichoke/blob/fccc282c8ef5063e6e3f55b22fd4998295b5bab1/spinoso-time/src/time/tzrs/convert.rs#L46-L59

**Comment by lopopolo** [comment]
Work on this is in progress:

- https://github.com/artichoke/strftime-ruby/pull/12

**Comment by lopopolo** [comment]
`strftime-ruby` v1.0.0 is released! https://github.com/artichoke/strftime-ruby/releases/tag/v1.0.0
