### ISSUE TITLE
Implement Range#cover?

### ISSUE THREAD

**Issue by lopopolo** [artichoke/artichoke#207]
https://ruby-doc.org/core-2.6.3/Range.html#method-i-cover-3F

Not sure if we can do this in Ruby.

The mruby implementation might be a good starting point.

https://github.com/artichoke/artichoke/blob/51f393863b93405a2ae2d4fdb34b80a2eb95055f/mruby-sys/vendor/mruby/mrbgems/mruby-range-ext/src/range.c#L42-L66

**Comment by tkbky** [comment]
Seems like we could implement this in Ruby, I'll take this.
