### ISSUE TITLE
The doc of `spinoso_time::tzrs::Time::day_of_year()` is inconsistent with its implementation

### ISSUE THREAD

**Issue by lopopolo** [artichoke/artichoke#2072]
The doc of `spinoso_time::tzrs::Time::day_of_year()` is inconsistent with its implementation:
https://github.com/artichoke/artichoke/blob/b3284a42fb0d175da1a822bda73bd300ddab72c3/spinoso-time/src/time/tzrs/parts.rs#L511-L533.

`tz::datetime::DateTime` returns a year day in `[0, 365]`, but the spinoso_time doc say it should be in `1..366` (`1..=366` is more correct I think).

_Originally posted by @x-hgg-x in https://github.com/artichoke/strftime-ruby/issues/12#issuecomment-1212120502_

**Comment by b-n** [comment]
Ah yes, this is also I noticed yesterday after paying with #1956. Nice to see it's fixed!
