### ISSUE TITLE
Add tests in `array::trampoline` and `string::trampoline` to check for `FrozenError`s in mutating APIs

### ISSUE THREAD

**Issue by lopopolo** [artichoke/artichoke#2086]
I think this is the first test that has ever been added to a `trampoline` module. Thanks for blazing the trail!

We should add tests like these to the trampolines for `Array` and `String` too.

_Originally posted by @lopopolo in https://github.com/artichoke/artichoke/pull/2081#discussion_r945347036_

https://github.com/artichoke/artichoke/blob/23e43073b54e2694984a4b3b2e480fd5770d3ced/artichoke-backend/src/extn/core/regexp/trampoline.rs#L181-L193

**Comment by choznerol** [comment]
I realized `String` and `Array` do not throw `FrozenError` like `Regexp` do, so we can't really check for the presence of `FrozenError`.

```console
$ ruby -ve '/abc/.send(:initialize, /xyz/)'  
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]
-e:1:in `initialize': can't modify frozen Regexp: /abc/ (FrozenError)
	from -e:1:in `<main>'

$ ruby -ve 'p "abc".send(:initialize, "xyz")'
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]
"xyz"

$ ruby -ve 'p [1,2,3].send(:initialize, [4,5,6])'
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]
[4, 5, 6]
```

**Comment by lopopolo** [comment]
This is true for the `initialize` method, but there are many other mutating methods on `Array` and `String` that should throw `FrozenError`. The idea was to add tests for all of those.

**Comment by choznerol** [comment]
Oh, I see! Then I'd like to work on this issue.
