### ISSUE TITLE
Implement `Array#append` and `Array#push` in Rust

### ISSUE THREAD

**Issue by lopopolo** [artichoke/artichoke#2115]
`Array#append` and `Array#push` take a list of arguments and extend an `Array` with them. Values are appended as is, even if they are arrays:

- https://ruby-doc.org/core-3.1.2/Array.html#method-i-append
- https://ruby-doc.org/core-3.1.2/Array.html#method-i-push

MRI implementation:

- https://github.com/ruby/ruby/blob/v3_1_2/array.c#L1330-L1354
- https://github.com/ruby/ruby/blob/v3_1_2/array.c#L1320-L1328

```c
/*
 *  call-seq:
 *    array << object -> self
 *
 *  Appends +object+ to +self+; returns +self+:
 *
 *    a = [:foo, 'bar', 2]
 *    a << :baz # => [:foo, "bar", 2, :baz]
 *
 *  Appends +object+ as one element, even if it is another \Array:
 *
 *    a = [:foo, 'bar', 2]
 *    a1 = a << [3, 4]
 *    a1 # => [:foo, "bar", 2, [3, 4]]
 *
 */
```

`Array#push` is currently implemented in Ruby by delegating to `Array#concat`, which is incorrect because `push` should not flatten `Array` arguments:

https://github.com/artichoke/artichoke/blob/da852668b8588935929b2e6cfb655586da23d575/artichoke-backend/src/extn/core/array/array.rb#L925-L930

https://github.com/artichoke/artichoke/blob/da852668b8588935929b2e6cfb655586da23d575/artichoke-backend/src/extn/core/array/array.rb#L1368

**Comment by anshulxyz** [comment]
Hi Ryan, I'd like to pick this up. If no has started working on it yet.

**Comment by lopopolo** [comment]
Sounds great @anshulxyz. Let me know here if you have any questions.

**Comment by anshulxyz** [comment]
I need to investigate source code. But what I'm immediately looking for are the test cases that check this feature. So that I will be running them while development.

**Comment by lopopolo** [comment]
This might be a good opportunity to add some. There's a functional test file called `array_test.rb` right next to the trampoline. You can also use the Ruby specs with the harness in the spec-runner directory.

**Comment by anshulxyz** [comment]
hi @lopopolo can you give me `airb` examples of "`push` should not flatten `Array` arguments"

because I do not see the flattening
```ruby
>>> [1,2,3].push([4])
=> [1, 2, 3, [4]]
```

**Comment by lopopolo** [comment]
This is the difference between `Array#push` and `Array#concat` in MRI:

```console
$ irb
[3.1.2] > a = [1, 2, 3]
=> [1, 2, 3]
[3.1.2] > b = [['a', 'b', 'c'], ['x', 'y', 'z']]
=> [["a", "b", "c"], ["x", "y", "z"]]
[3.1.2] > a.push b; nil
=> nil
[3.1.2] > a
=> [1, 2, 3, [["a", "b", "c"], ["x", "y", "z"]]]
[3.1.2] > z = [1, 2, 3]
=> [1, 2, 3]
[3.1.2] > z.concat b; nil
=> nil
[3.1.2] > z
=> [1, 2, 3, ["a", "b", "c"], ["x", "y", "z"]]
```

In `concat`, the array is un-nested one level.

**Comment by lopopolo** [comment]
I think I see what is going on:

`Array#push` is defined here with a varargs:

https://github.com/artichoke/artichoke/blob/fbbe64921cc735639d6b165083aef01321531199/artichoke-backend/src/extn/core/array/array.rb#L921-L926

This is not obviously correct to me even if it has the right behavior. Regardless of whether the existing Ruby implementation of `Array#push` is correct, I'd still like to see it implemented in Rust since my preference is to implement all allocating Array operations in Rust.

**Comment by Tseyang** [comment]
@lopopolo This thread seemed quiet for a while so I took a stab at converting `push` to Rust in #2309.

**Comment by anshulxyz** [comment]
I haven't had time for this. Please feel free to take over this issue.

**Comment by rbxbx** [comment]
Looks like this issue was resolved 2 weeks ago by https://github.com/artichoke/artichoke/pull/2309 being merged :)

**Comment by lopopolo** [comment]
Thanks @rbxbx I missed closing this
