### ISSUE TITLE
Extract `absolutize_relative_to` to `scolapasta-path`

### ISSUE THREAD

**Issue by lopopolo** [artichoke/artichoke#2179]
This path normalization utility lives in `artichoke-backend`.

https://github.com/artichoke/artichoke/blob/2fe83803834963deef45e5fa8a295188902b72b7/artichoke-backend/src/load_path.rs#L66-L246

Move it and its tests to `scolapasta-path`. Does this need more tests?

I'm not convinced that this function is the best way to do this and maybe we can delegate to a third party crate. Some requirements:

- Does not rely on `std::fs::canonicalize` because this routine may be used on paths in virtual filesystems.
- Correctly handles various Windows path prefixes including verbatim paths: https://doc.rust-lang.org/stable/std/path/enum.Prefix.html
- Produces paths with `/` as the path separator (for non-verbatim paths on Windows). This can be done by collecting the `Component`s into an `OsString` with `Component::as_os_str`.

It looks like the current implementation is missing tests that the string representation of the path has `/` path separators on Windows.

**Comment by lopopolo** [comment]
As we do this extraction, let's do the trick that minimizes the code bloat from monomorphization while still getting the ergonomics with `AsRef<Path>` and restructure the code like:

```rust
pub fn absolutize_relative_to<T, U>(path: T, cwd: U) -> PathBuf
where
    T: AsRef<Path>,
    U: AsRef<Path>,
{
    absolutize_relative_to_inner(path.as_ref(), cwd.as_ref())
}

fn absolutize_relative_to_inner(path: &Path, cwd: &Path) -> PathBuf {
    todo!();
}
```

**Comment by NlightNFotis** [comment]
Hello @lopopolo .

I am aware of a Windows-specific requirement for this issue - I am sadly not in the position to check it because I lack access to any windows machines (all of my machines are `aarch64`).

Let me know if there's something else I can do to either fulfil the requirement or otherwise compensate for the lack of it.

**Comment by lopopolo** [comment]
Thanks @NlightNFotis. I can take a look at the windows bits but it probably won't be until the new year. Happy holidays and thanks for the PR.
