### ISSUE TITLE
Implement Math module in Rust

### ISSUE THREAD

**Issue by lopopolo** [artichoke/artichoke#222]
This module is a collection of pure functions. It should be straightforward to extract numbers with converters, call math functions from `std`, and wrap the result in a `Value`.

**Comment by cdeler** [comment]
@lopopolo I would be happy, if I can take it

**Comment by lopopolo** [comment]
Thanks @cdeler it's all yours 💎

**Comment by lopopolo** [comment]
Fixed in GH-559.
