### ISSUE TITLE
Add support for `Regexp` needles to `String#byteindex`

### ISSUE THREAD

**Issue by lopopolo** [artichoke/artichoke#2359]
https://github.com/artichoke/artichoke/pull/2358 added the [`String#byteindex`] API but did not add support for `Regexp` patterns, like:

[`String#byteindex`]: https://ruby-doc.org/3.2.0/String.html#method-i-byteindex

```ruby
'foo'.byteindex(/f/) # => 0
'foo'.byteindex(/o/) # => 1
'foo'.byteindex(/oo/) # => 1
'foo'.byteindex(/ooo/) # => nil
```

I am not sure what the behavior of this function is when given a regexp and an offset arg.

The current code raises `NotImplementedError`. This is where the implementation must go:

https://github.com/artichoke/artichoke/blob/8460b3faef4c344dcf46f58086595e3f2b27660f/artichoke-backend/src/extn/core/string/trampoline.rs#L588-L591

See also:

- https://github.com/artichoke/artichoke/issues/2362

**Comment by do-you-dare** [comment]
Hello! I'd like to try this one, may I? My plan is to see other methods supporting regexp needles to use as reference.

**Comment by lopopolo** [comment]
@do-you-dare Sounds great. I'd love to see you take a stab at this one 💪

**Comment by do-you-dare** [comment]
Hello! I'm working on this, slowly, as I'm still getting acquainted with rust and the project structure, but working. I didn't find specs for `byteindex` at `spec-runner/vendor/spec/core/string`, should I add a test there later or just adding a test to `artichoke-backend/src/extn/core/string/string_test.rb` enough?

**Comment by lopopolo** [comment]
The various `vendor` directories sprinkled throughout the codebase contain code from upstream dependencies (usually tracked separately as forks within the @artichoke organization. Please don't make changes to them.

Separately, the vendored Ruby specs are out of date, blocked on upgrading MSpec, which is blocked on adding some API coverage to `Hash`.

Please add tests to `string_test.rb`. These are Artichoke specific functional tests.
