### ISSUE TITLE
Naming of internal packages

### ISSUE THREAD

**Issue by sandstrom** [artichoke/artichoke#2693]
I don't have detailed understanding of this project, but I like the idea and want it to succeed.

However, I think the internal naming of packages is confusing. Mezzaluna, scolapasta, spinoso… it doesn't help newcomers.

I'd keep the artichoke name, but for every intra-project component, I'd rename them to something that makes sense (`core-…`, `internal-…`). If you are also publishing these as cargo packages, there must still be a better name, e.g. `ruby-…` or `artichoke-core-…`.

**Comment by lopopolo** [comment]
Hi @sandstrom thanks for the question. These prefixes represent logical groupings of crates. For example, spinoso crates are used to implement the Ruby core and standard libraries.

This is outlined both in prose and diagram in https://github.com/artichoke/artichoke/blob/trunk/ARCHITECTURE.md.

Although taking a look I see that the mezzaluna crate type is missing. That one is utilities meant to be consumed by the VM and front end crates.

Is there anything about the docs that can be made more clear? I am not interested in renaming things at this time.

**Comment by sandstrom** [comment]
@lopopolo It's a good explanation, and it certainly helps. 

I would still consider renaming, but also understand if you don't want to spend time on that right now.

**Comment by sandstrom** [comment]
@lopopolo It's a good explanation, and it certainly helps. 

I would still consider renaming, but also understand if you don't want to spend time on that right now.
