### ISSUE TITLE
Awareness opportunity: add to asdf/mise plugin

### ISSUE THREAD

**Issue by ylluminate** [artichoke/artichoke#2695]
Just a thought that might add to awareness/ease of installation: add to the asdf plugin that is also able to be used for mise: https://github.com/asdf-vm/asdf-ruby

**Comment by lopopolo** [comment]
Thanks for the ticket, but I don't think there is anything to do here. Artichoke nightlies are already distributed via `ruby-build`.

`mise` itself is broken in that it adds a check for the `gem` executable on top of `ruby-build` which prevents alternative rubies like Artichoke and mruby from installing.

**Comment by jdx** [comment]
I'd accept a pr to remove the check for some rubies or something like that
