### ISSUE TITLE
Private vulnerability reporting

### ISSUE THREAD

**Issue by Sim4n6** [artichoke/artichoke#2707]
Hey ,

I have identified a potential vulnerability in the latest codebase [artichoke/artichoke](https://github.com/artichoke/artichoke).

Could you please consider enabling the GitHub feature for [private vulnerability reporting](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository) to smooth the disclosure process ? or in case if you have a bug bounty program, please send me an invitation.

Thank you
@Sim4n6

**Comment by lopopolo** [comment]
Please send an email to github@artichokeruby.org. Thanks

**Comment by Sim4n6** [comment]
Email sent.

**Comment by Sim4n6** [comment]
Any update on this one ?

**Comment by lopopolo** [comment]
This report was invalid. It contained ~60 instances of Ruby code and functions in Core that loop, which are the expected behavior.
