### ISSUE TITLE
Add artichoke to platform detection in mspec

### ISSUE THREAD

**Issue by lopopolo** [artichoke/artichoke#272]
Update this commit in artichoke/mspec and revendor MSpec:

https://github.com/artichoke/mspec/commit/8c266ab5c65858b8cb39e9e8931c7a3a45966011

_Originally posted by @lopopolo in https://github.com/artichoke/artichoke/pull/271#issuecomment-529060732_

**Comment by navkumar2245** [comment]
can I work on this issue if nobody working on it?

**Comment by lopopolo** [comment]
If you’d like. This is a bit of a weird ticket in that it requires touching two repos. If you’d like to sync MSpec with the latest upstream maste that’d be great too 💎

**Comment by lopopolo** [comment]
This is no longer necessary upstream.

https://twitter.com/eregontp/status/1186719295465672705
