### ISSUE TITLE
Clarify airb command in Readme

### ISSUE THREAD

**Issue by nicholalexander** [artichoke/artichoke#319]
As someone who is entirely new to Rust and thusly Artichoke, but not new to Ruby, I was confused by the instructions in the Try Artichoke section.  Mostly because of the words "frontend" and "airb" - which I at first thought had something to do with the WebAssembly build and some reference to AirBnB?  

Only after reading through things did it make sense about what the artichoke frontend and backend are and what airb is!  Small change but I'd suggest some clarifying wording to that section - something along the lines of:

```makrdown
If you would prefer to run a local build, you can
[set up a Rust toolchain](/CONTRIBUTING.md#rust-toolchain) and launch an
interactive Artichoke shell with the Artichoke version of `irb`, `airb`:
```

I make this suggestion with the hope being that it would make the project more inviting to spin up and start experimenting with.  It is also entirely possible that this suggestion is only relevant to me.  Happy to fork and make an actual PR for this if it is at all valuable.

**Comment by lopopolo** [comment]
Hi  @nicholalexander I love your suggestion. That makes things clearer.

But since this is a point of confusion, how would you feel about just generating an irb executable? We do this already for the artichoke and ruby binaries.

Would you like to submit a PR with a symlink from irb -> airb as well as a README change?

**Comment by nicholalexander** [comment]
Great!  Thanks for the feedback!  I will try to do this!

Also, I didn't say in my previous comment but I love this project and think it's really interesting!  Awesome work to everyone working on this.
