### ISSUE TITLE
Implement String#index with bstr for String patterns

### ISSUE THREAD

**Issue by lopopolo** [artichoke/artichoke#323]
String#index is a specialized version of String#scan.

It might be possible to implement String#index in terms of String#scan, but it will likely be more efficient to create a specialized impl.

**Comment by aivensong** [comment]
@lopopolo i can work on this

**Comment by lopopolo** [comment]
@aivensong sounds good

**Comment by sudopluto** [comment]
going to try to take this one, will review previous pull request

**Comment by AlyHKafoury** [comment]
can I work on this @lopopolo ? or is it done ?

**Comment by lopopolo** [comment]
Hi @AlyHKafoury. Yes you can work on this.

`spinoso-string` is the place this should live now: https://github.com/artichoke/artichoke/tree/trunk/spinoso-string.
