### ISSUE TITLE
Implement Time class in Ruby Core

### ISSUE THREAD

**Issue by lopopolo** [artichoke/artichoke#33]
In MRI, `Time` is both a [Core class](https://ruby-doc.org/core-2.6.3/Time.html) and a [Standard Library package](https://ruby-doc.org/stdlib-2.6.3/libdoc/time/rdoc/Time.html).

The Core class is implemented in C, see [`time.c` in CRuby](https://github.com/ruby/ruby/blob/v2_6_3/time.c). Reimplement this class in Rust with [httpdate](https://docs.rs/httpdate/) and [chrono](https://docs.rs/chrono/).

The Standard Library package is pure Ruby and can likely be imported as is once the Core class is in place. See GH-158 for an example of how to do this.

Remove dependency on `mruby-time` mrbgem.

**Comment by vaibhav-y** [comment]
I'm familiar with C and the ruby-c-api from some time back, would you say this is a good issue to start with, given that libraries to handle time exist / the code to port is reasonable?

Also, how does one get started contributing to this repo? I'm picking up rust as a new language, I come from a strong C++ background.

**Comment by lopopolo** [comment]
Hi @vaibhav-y 👋 I would love to leverage your experience to help implement Artichoke.

I've added a [`CONTRIBUTING.md`](https://github.com/artichoke/artichoke/blob/master/CONTRIBUTING.md) which outlines how to get set up so you can build the code and run the tests.

The time package in MRI has both C and Ruby pieces to it. Artichoke has implemented `Regexp` already which [follows a similar pattern](https://github.com/artichoke/artichoke/blob/master/artichoke-backend/src/extn/core/regexp/mod.rs).

For handling the time bits, we can probably use some combination of [httpdate](https://docs.rs/httpdate/) and [chrono](https://docs.rs/chrono/).

One thing Artichoke does that is maybe _non-obvious Rust_ is make heavy use of `Rc` and interior mutability with `RefCell`. You can check out [`manual.rs`](https://github.com/artichoke/artichoke/blob/189961ad97b9fbda1e3341fe0ede5495b2d26c2d/artichoke-backend/tests/manual.rs) for a self-contained example of how this works.

I hope this is enough to get started and I'm happy to answer any questions you have along the way.  I'm excited to have you contribute 💎

**Comment by vaibhav-y** [comment]
Thanks for all the information! I will keep you posted on developments, for now I'm reading through the items you've sent me, and also figuring out a mind map for using rust. Is there an IRC channel or group somewhere we keep in touch regarding general questions & such?

**Comment by lopopolo** [comment]
If you find chat conversations to be higher bandwidth, I've created a discord server, which you can join by clicking: https://discord.gg/QCe2tp2

I'll be adding this info to the `CONTRIBUTING` guidelines soon. Thanks for the push.

**Comment by lopopolo** [comment]
@vaibhav-y I've updated the issue description to reflect that this issue is focused on implementing `Time` as defined in [Ruby Core](https://ruby-doc.org/core-2.6.3/Time.html).

**Comment by vaibhav-y** [comment]
Ack.

**Comment by lopopolo** [comment]
hey @b-n I'm doing some backlog grooming and found this ancient issue. I think we can close this?

If yes, please do the honors as this is a result of your hard work 💪

**Comment by b-n** [comment]
Oh nice :broom:ing.

Yeah, I think this makes sense to close. A quick grep for `mruby-time` only shows things in `vendor/` which feels like that's the main goal here :-D.
