### ISSUE TITLE
Implement Kernel#rand and SecureRandom in Rust

### ISSUE THREAD

**Issue by lopopolo** [artichoke/artichoke#34]
Remove dependency on `mruby-random` mrbgem.

**Comment by lopopolo** [comment]
We should be able to use the [rand crate](https://docs.rs/rand) to implement this in pure Rust.

**Comment by Elang89** [comment]
If this hasn't been resolved yet, I'd like to try my luck with it.

**Comment by lopopolo** [comment]
It's all yours @Elang89 

One gotcha is you'll need to remove the `SecureRandom` stub:

https://github.com/artichoke/artichoke/blob/3d715c9a22f22b78460e6681bf634e85dfb7e62b/artichoke-backend/src/extn/stdlib/stubs.rs#L12-L15

**Comment by lopopolo** [comment]
We'll also probably need the `uuid` crate with the `v4` feature.

**Comment by lopopolo** [comment]
It looks like this API is implemented in Ruby and selects a backend such as openssl. I think we can do better by implementing in pure Rust and avoiding an openssl dependency.

https://github.com/artichoke/artichoke/blob/3d715c9a22f22b78460e6681bf634e85dfb7e62b/artichoke-backend/vendor/ruby/lib/securerandom.rb

**Comment by lopopolo** [comment]
Kernel#rand was implemented in GH-384.
