### ISSUE TITLE
module_function does not work as intended

### ISSUE THREAD

**Issue by zaccari** [artichoke/artichoke#408]
First, just want to say that I'm having a lot of fun with Artichoke. Thank you so much for putting this tool together.

While attempting to implement the [`Abbrev`](https://github.com/artichoke/artichoke/issues/74) module, I came across this weird scenario where the linter complains about `module_function`:

```
Style/AccessModifierDeclarations: module_function should not be inlined in method definitions
```

Yet when I declare it before the function, I'm not able to access it. Here's a stripped down example:

```ruby
module Foo
  module_function
  def bar
    "Hello world"
  end
end
```

When I run in IRB:

```bash
2.6.3 :014 > Foo.bar
 => "Hello world"
```

And here's what I get in AIRB:

```bash
>>>  Foo.bar
Backtrace:
    (airb):2: undefined method 'bar' (NoMethodError)
    (airb):2
```

However, if I use the original code (that the linter complains about), I'm able to access it in AIRB:

```ruby
module Foo
  def bar
    "Hello world"
  end
  module_function :bar
end
```

```bash
>>> Foo.bar
=> "Hello world"
```

**Comment by lopopolo** [comment]
This is a known limitation in Artichoke. `Module#module_function` is a NOOP if passed no arguments. `Module#private`, `Module#public`, and `Module#protected` are NOOPs always (all methods are public).

Suppressing the linter is the right thing to do here. There are instances of this elsewhere in the project:

https://github.com/artichoke/artichoke/blob/5f8628276d0f8c0de798832a52876c29fe7f1671/artichoke-backend/src/extn/core/enumerator/enumerator.rb#L295

or this rewrite of upstream Ruby JSON pure sources: https://github.com/artichoke/artichoke/commit/b90b345fe103ede88809b9cbef904c63a5d8d732

It looks like you came to the right conclusion to suppress the lint violation with a rubocop pragma. Thanks 😄

**Comment by zaccari** [comment]
Ah gotcha! Thank you for clarifying
