### ISSUE TITLE
Dividing two integers returns a float

### ISSUE THREAD

**Issue by CodeGradox** [artichoke/artichoke#410]
While testing artichoke against ruby 2.6.3 I noticed I got different results when running a program. Turns out artichoke returns a float instead of an int when dividing two integers.
Is this intentional or a bug?

**Comment by lopopolo** [comment]
Hi @CodeGradox thanks for reporting this. This is both a limitation of Artichoke (missing method impl in Fixnum) and a limitation of the mruby VM Artichoke build atop (which we embed and actively modify).

Both of these deficiencies are fixed in GH-411.

**Comment by CodeGradox** [comment]
Thanks for the quick fix.
I was working on advent of code and was a bit disappointed with ruby's performance so I wanted to compare with artichoke. There as still a few features missing so I can't run most of my solutions.
Maybe artichoke will be good enough for the next years calendar.

Keep up the good work! :+1:
