### ISSUE TITLE
Need to have `p` method

### ISSUE THREAD

**Issue by Madao-3** [artichoke/artichoke#440]
We have `puts`  and `print`, but we don't have  `p` method.

**Comment by lopopolo** [comment]
I’m not too familiar with `p`. I wonder if it can be implemented in pure Ruby.

**Comment by matugm** [comment]
From the Ruby docs:

> "For each object, directly writes obj.inspect followed by a newline to the program's standard output."


https://devdocs.io/ruby~2.6/kernel#method-i-p

MRI implementation:

https://github.com/ruby/ruby/blob/e51b6aa81dcad4f07021fbd986050e1995770855/io.c#L7849

Hope that helps :)

**Comment by jonkgrimes** [comment]
Hello! I took a stab at this and would love feedback.
