### ISSUE TITLE
Add docs for how to build

### ISSUE THREAD

**Issue by lopopolo** [artichoke/artichoke#55]
- Wasm
- native
- cross

**Comment by Lewiscowles1986** [comment]
Is Wasm & Native not documented in https://github.com/artichoke/artichoke/blob/master/.circleci/config.yml?

**Comment by lopopolo** [comment]
@Lewiscowles1986 it is. There are some yarn scripts that make it nicer locally and I think having it in human readable markdown would be a better experience.

Do you want to take a stab at this?

**Comment by Lewiscowles1986** [comment]
* [ ] wasm
* [ ] native
* [ ] cross

**Comment by lopopolo** [comment]
Building `mruby-sys` currently depends on a `clang` toolchain being installed + `bintools` + `yacc` + `gperf` + `ruby`.

https://github.com/artichoke/artichoke/blob/6ad780b1a9899155bc7fe9a71a5b8eb3d16acc2f/.circleci/config.yml#L48-L61

See GH-137.
