### ISSUE TITLE
Investigate adding UI tests for artichoke binary frontend

### ISSUE THREAD

**Issue by lopopolo** [artichoke/artichoke#595]
https://github.com/artichoke/artichoke/pull/594 added backtrace formatting to `artichoke` binary.

It is unclear how to test such a behavior change in Artichoke now.

[`rustc` has a suite of UI tests](https://github.com/rust-lang/rust/tree/master/src/test/ui) that test the output of the compiler in various circumstances.

In addition to testing that stacktraces get formatted correctly, we might want to test that `puts` uses `#to_s` and `pp` uses `#inspect`. Or that ANSI escapes make it to the output properly.

**Comment by phansch** [comment]
Maybe [`insta`](https://github.com/mitsuhiko/insta) is a good fit for this?

**Comment by lopopolo** [comment]
`insta` looks like it will fit the bill.

The tricky part is reworking the Artichoke output state to allow overrides without using cargo features. Otherwise, a unit test would have no way to capture `stdout` and `stderr`.

Capturing `stdout` is required for testing things like `puts`, `print`, and `p`.
Capturing `stdout` is required for `Warning::warn`, `Kernel::warn`, and built in warnings from core types like `Regexp` which are emitted from Rust.

**Comment by lopopolo** [comment]
The regression addressed in https://github.com/artichoke/artichoke/pull/976 might have been prevented if there were UI tests for `airb`. `airb` is a readline shell which I believe requires a tty.
