### ISSUE TITLE
chruby and artichoke compability

### ISSUE THREAD

**Issue by deepj** [artichoke/artichoke#653]
I prepared PR (https://github.com/rbenv/ruby-build/pull/1438) adding Artichoke to [ruby-build](https://github.com/rbenv/ruby-build) and I would like to use it with [chruby](https://github.com/postmodern/chruby).

But there is a problem with switching when chruby calls this in its bash script:

```bash
echo "$("$RUBY_ROOT/bin/ruby" - <<EOF
puts "export RUBY_ENGINE=#{defined?(RUBY_ENGINE) ? RUBY_ENGINE : 'ruby'};"
puts "export RUBY_VERSION=#{RUBY_VERSION};"
begin; require 'rubygems'; puts "export GEM_ROOT=#{Gem.default_dir.inspect};"; rescue LoadError; end
EOF
)"
```

From https://github.com/postmodern/chruby/blob/824db2625aa78d1bce2fd25c2fc9be76f161b332/share/chruby/chruby.sh#L46-L51

I got this error

```
LoadError (No such file or directory -- -)
```

The problem lies in how artichoke interprets `ruby -<<EOF .. EOF>>` in the bash script and sees it as a file instead of interpreting code as the rest Ruby implementation

**Comment by lopopolo** [comment]
GH-654 fixes the `-` as filename bug, but Artichoke will remain incopatible with chruby. Copying comment from GH-654 below:


    $ ./target/debug/artichoke - <<EOF
    puts "export RUBY_ENGINE=#{begin; Object.const_get(:RUBY_ENGINE); rescue NameError; 'ruby'; end};"
    puts "export RUBY_VERSION=#{RUBY_VERSION};"
    begin; require 'rubygems'; puts "export GEM_ROOT=#{Gem.default_dir.inspect};"; rescue LoadError; end
    EOF
    export RUBY_ENGINE=artichoke-mruby;
    export RUBY_VERSION=2.6.3;

Artichoke does not support `defined?`, so to get the chruby script to
execute, I had to replace it with `Object.const_get`.

**Comment by deepj** [comment]
@lopopolo or `Object.const_defined?(:RUBY_ENGINE)` 😹 That's unfortunately supported by Artichoke 😼

**Comment by deepj** [comment]
In fact, it's already fixed in chruby master
