### ISSUE TITLE
Return Result from ArenaIndex::new

### ISSUE THREAD

**Issue by lopopolo** [artichoke/artichoke#669]
with the addition of `Artichoke::with_ffi_boundary`, this API is now fallible.

propagate an error instead of unwrapping.

use a custom error type that implements `RubyException`.

https://github.com/artichoke/artichoke/blob/e4eb05edb4a08c4463f4a206cb8fb3895ceda6b0/artichoke-backend/src/gc/arena.rs#L35-L39

**Comment by lopopolo** [comment]
introduced in GH-661

**Comment by lopopolo** [comment]
For a look at how to implement a custom `RubyException`, see `InterpreterAllocError` in `artichoke-backend/src/interpreter.rs`.

**Comment by druzn3k** [comment]
I would love to try with this issue

**Comment by druzn3k** [comment]
So, I modified the PR per request. Now `ArenaIndex::new` returns a `Result<ArenaIndex, IndexError>` instead of the `InterpreterError`.
