### ISSUE TITLE
Implement Symbol#inspect

### ISSUE THREAD

**Issue by lopopolo** [artichoke/artichoke#725]
Requires: https://github.com/artichoke/artichoke/issues/219

**Comment by dnamsons** [comment]
Is is possible to work on this?

**Comment by lopopolo** [comment]
Yes. Please, go for it 👍

**Comment by dnamsons** [comment]
@lopopolo Thanks! 

I'm pretty sure on how to go about implementing this up to the point where specific encoding is required, e.g. 
`:''.inspect => ":\"\""`

Do you have any tips or ideas on how one might approach this?

**Comment by lopopolo** [comment]
This function will handle unicode escapes for non UTF-8 characters.

https://github.com/artichoke/artichoke/blob/039f1a01c4f2a983c2b4ef9734fe856d7ff8757b/artichoke-backend/src/string.rs#L22-L61

I wouldn't worry about encoding. Artichoke treats all strings as maybe UTF-8.

**Comment by lopopolo** [comment]
Oh I don't know if this was clear from the issue description, but this function is best implemented in Rust.
