### ISSUE TITLE
Expose Time#saturday? to Ruby code

### ISSUE THREAD

**Issue by lopopolo** [artichoke/artichoke#735]
In Ruby Core, the `Time` class has a [`saturday?` method][saturday]. Expose this method on on the VM so that it is callable from Ruby code.

This issue will walk though an example using the [`wday` method][weekday] that returns the day of the week as an `Integer` that a `Time` represents.

Exposing a native method on the Artichoke VM uses a series of [trampolines] to move from an mruby context to a Rust context with native types.

Core classes typically have an outer API shell that delegates to one or more implementations of an internal "backend" API.

For the `Time` class, backends implement the `TimeType` trait which defines a `weekday` method:

https://github.com/artichoke/artichoke/blob/39eb05b3b59a9cf2c7302eff8f529ee51f933d60/artichoke-backend/src/extn/core/time/backend/mod.rs#L37

The only backend for `Time` is one based on [`chrono`]. It implements `TimeType::weekday` like this:

https://github.com/artichoke/artichoke/blob/39eb05b3b59a9cf2c7302eff8f529ee51f933d60/artichoke-backend/src/extn/core/time/backend/chrono.rs#L61-L63

To complete the implementation, we must add two trampolines to wire this API up to the VM.

There is a Rust trampoline in `trampoline.rs` in every `extn` module that marshals from the Rust version of a boxed Ruby value to native types and back.

https://github.com/artichoke/artichoke/blob/39eb05b3b59a9cf2c7302eff8f529ee51f933d60/artichoke-backend/src/extn/core/time/trampoline.rs#L59-L64

Next there is an mruby trampoline which is the FFI adpater between the mruby C VM and Rust. This is the x-language entrypoint:

https://github.com/artichoke/artichoke/blob/39eb05b3b59a9cf2c7302eff8f529ee51f933d60/artichoke-backend/src/extn/core/time/mruby.rs#L161-L175

`mrb_get_args!` is a macro that extracts method arguments from the underlying C interpreter. For `Time#wday`, you should use `mrb_get_args!(mrb, none)` since `Time#wday` takes zero arguments.

Once the trampolines are in place, wire everything up as a callable method:

https://github.com/artichoke/artichoke/blob/39eb05b3b59a9cf2c7302eff8f529ee51f933d60/artichoke-backend/src/extn/core/time/mruby.rs#L23

Once everything is wired up, this should successfully print out whether it is saturday:

```
cargo run --quiet --bin artichoke -- -e 'puts Time.now.wday' -e 'puts Time.now.saturday?'
```

[saturday]: https://ruby-doc.org/core-2.6.3/Time.html#method-i-saturday-3F
[weekday]: https://ruby-doc.org/core-2.6.3/Time.html#method-i-wday
[trampolines]: https://en.wikipedia.org/wiki/Trampoline_(computing)
[`chrono`]: https://docs.rs/chrono/0.4.12/chrono/

**Comment by lopopolo** [comment]
Does this look like something you'd want to work on @druzn3k?

**Comment by druzn3k** [comment]
absolutely @lopopolo  :)

**Comment by lopopolo** [comment]
Closed by GH-736.
