### ISSUE TITLE
Use case as a scripting language

### ISSUE THREAD

**Issue by erlend-sh** [artichoke/artichoke#749]
With the advent of [WASM as a Platform for Abstraction](https://users.rust-lang.org/t/wasm-as-a-platform-for-abstraction/35736?u=erlend_sh), Ruby/artichoke seems like an excellent way to do scripting on any platform that uses WASM in this way.

https://github.com/timberio/vector/pull/2341

In a somewhat similar vein, I’m curious what you think about using Ruby/artichoke as the extension language for a Rust framework such as actix-web or Rocket. This strikes me as a very powerful combo: Rust takes care of the underlying framework, whereas Ruby is used for most of the application code.

**Comment by lopopolo** [comment]
Hi @erlend-sh. Thanks for reaching out. This use case is very aligned with Artichoke's goals. From [`VISION.md`]:

- Support WebAssembly as a build target.
- Support embedding and executing Ruby in untrusted environments.

To your first question about Wasm scripting, Artichoke does intend to compile to native Wasm. It currently requires emscripten. See https://github.com/artichoke/artichoke/issues/54#issuecomment-590076073 for our long-term approach.

Using Artichoke and Ruby as an extension language for Rust is within scope for this project.

You might be interested to learn more about Artichoke's history to see why this is the case:

- Artichoke was originally born out of [rube], which used Ruby as a server-side scripting language in a polyglot webapp.
- [ferrocarril](https://github.com/artichoke/ferrocarril) is an early version of Artichoke that [implemented a `rack` compatible webserver with Rocket][nemesis] and could execute [Sinatra webapps].
- Artichoke has a [Rust-native extension API] that functions similarly to C rubygem extensions in MRI. This API is used to implement [`SecureRandom` in Ruby Standard Library] and a [wrapper around `stdweb`] in the artichoke/playground

Artichoke's standard library (and eventually VM) exposes cargo features to limit functionality in ways that make Artichoke easier to use when executing untrusted code. For example, disabling `Regexp` engines that might fail with exponential backtracking, disabling access to the system environ, or limiting the scope/disabling native filesystem access.

https://github.com/artichoke/artichoke/blob/350e3dbdda45bad0d216539e3e03f3a9d7c4fbfe/Cargo.toml#L53-L77

[`VISION.md`]: https://github.com/artichoke/artichoke/blob/350e3dbdda45bad0d216539e3e03f3a9d7c4fbfe/VISION.md
[rube]: https://github.com/lopopolo/rube
[nemesis]: https://github.com/artichoke/ferrocarril/tree/master/nemesis
[Sinatra webapps]: https://github.com/artichoke/ferrocarril/blob/master/hubris/src/echo_server.rb
[Rust-native extension API]: https://artichoke.github.io/artichoke/artichoke_core/file/trait.File.html
[`SecureRandom` in Ruby Standard Library]: https://github.com/artichoke/artichoke/blob/350e3dbdda45bad0d216539e3e03f3a9d7c4fbfe/artichoke-backend/src/extn/stdlib/securerandom/mruby.rs#L9-L50
[wrapper around `stdweb`]: https://github.com/artichoke/playground/blob/23cffce91ede6e071073cce0d6adc0a9928dc82d/playground/src/web/mod.rs
