### ISSUE TITLE
Implement base64 standard library package

### ISSUE THREAD

**Issue by lopopolo** [artichoke/artichoke#75]
[`bas64`](https://ruby-doc.org/stdlib-2.6.3/libdoc/base64/rdoc/index.html) is a pure Ruby package.

To add this package to the standard lib of Artichoke:

- Update mruby dependency to pull in the fix for https://github.com/mruby/mruby/issues/4556 because base64 depends on `String#pack`

      $ git clone git@github.com:mruby/mruby.git
      $ cd mruby
      $ cp -r ". /path/to/artichoke/mruby-sys/vendor/mruby-$(git rev-parse --short HEAD)"
      $ cd /path/to/artichoke
      # then edit mruby-sys/build.rs to point to the new sha
      $ cargo build
      $ cargo test
      $ git rm -r mruby-sys/vendor/mruby-bc7c5d3
      $ rm -rf mruby-sys/vendor/mruby-*/.git
      $ git add .
      $ git commit
- Import the [Ruby 2.6.3 sources](https://github.com/ruby/ruby/blob/v2_6_3/lib/base64.rb).
- Make a commit here.
- RuboCop the source files.
  - Run automatic fixups with `yarn lint`. Make a commit here.
  - Manually fixup until linter passes. Make a commit here.
- Add Rust glue, [like this example for `ostruct`](https://github.com/artichoke/artichoke/blob/13c2181738ee34225cbadd5f4ac6c188bda6415d/artichoke-backend/src/extn/stdlib/ostruct.rs). Make a commit here.
- [Add test for spec compliance](https://github.com/artichoke/artichoke/blob/13c2181738ee34225cbadd5f4ac6c188bda6415d/scripts/spec-compliance.sh#L27). Make a commit here.
- Run spec compliance tests with `yarn spec`.
- If the tests pass, 🎉. If they do not, there is likely a bug in Artichoke or an upstream bug in mruby. We can discuss in this issue how to proceed.

**Comment by kenaniah** [comment]
@lopopolo I'd like to give this a shot

**Comment by lopopolo** [comment]
@kenaniah This should be much easier now that we auto-generate Rust glue for Ruby standard library packages.

https://github.com/artichoke/artichoke/pull/158 should be a good thing to base this PR on.
