### ISSUE TITLE
Integrate CactusRef into Artichoke VM

### ISSUE THREAD

**Issue by lopopolo** [artichoke/artichoke#81]
[CactusRef](https://github.com/artichoke/cactusref) [[docs](https://artichoke.github.io/cactusref/cactusref)] [[blog](https://hyperbo.la/w/cactus-harvesting/)] is a cycle-aware smart pointer that does deterministic garbage collection when objects (and cycles) become externally unreachable.

CactusRef has an API that is mostly compatible `std::rc::Rc` in the Rust Standard Library.

Wrap `Value`s in `cactusref::Rc` as part of the core VM.

CactusRef only supports single threaded accesses as of 2019-08-02.

**Comment by lopopolo** [comment]
It is unlikely that `CactusRef` is the right choice for GC.

**Comment by ajeetdsouza** [comment]
Hey @lopopolo, could you comment on what your learnings from CactusRef were, and why you decided that it was not a good fit for a GC?

**Comment by lopopolo** [comment]
Hi @ajeetdsouza, the big reason is that `cactusref` requires several unstable `std` features and will likely require nightly Rust for quite some time:

```
#![feature(
    allocator_api,
    core_intrinsics,
    dropck_eyepatch,
    layout_for_ptr,
    set_ptr_value,
    slice_ptr_get
)]
```

https://github.com/artichoke/cactusref/blob/1fac53574c537279cdcdd0c1aebc87e7fc433ad5/src/lib.rs#L1-L8

I'm not the most satisfied with the adoption API and I'm not sure the `unsafe fn` are in the right place to make the library ergonomic to use: https://github.com/artichoke/cactusref/pull/47.

Additionally, the crate is likely full of unsoundness and memory leaks and I don't have the energy to invest in fixing those if I don't have an immediate use case for this code.

If you're curious in using `cactusref`, I'd be happy to accept PRs over in https://github.com/artichoke/cactusref.

**Comment by ajeetdsouza** [comment]
That makes sense, thank you for clarifying!
