### ISSUE TITLE
Implement Array#clear in Rust

### ISSUE THREAD

**Issue by lopopolo** [artichoke/artichoke#965]
`Array#clear` is currently implemented in Ruby:

https://github.com/artichoke/artichoke/blob/a2229d9de0a0b2f885e2392b0414a4f9589a4b1f/artichoke-backend/src/extn/core/array/array.rb#L332-L335

This implementation is less efficient than it could be because it computes a slice drain and reads all of the elements.

`Array#clear` could easily be implemented with `Array::clear` in Rust:

https://github.com/artichoke/artichoke/blob/a2229d9de0a0b2f885e2392b0414a4f9589a4b1f/artichoke-backend/src/extn/core/array/mod.rs#L183-L185

## Implementation guide

Following the implementation of `Array#concat` as an example:

1. `Array#clear` already has a trampoline defined for it:
  https://github.com/artichoke/artichoke/blob/a2229d9de0a0b2f885e2392b0414a4f9589a4b1f/artichoke-backend/src/extn/core/array/trampoline.rs#L7-L21
2. Define an mruby C entrypoint for clear:
  https://github.com/artichoke/artichoke/blob/a2229d9de0a0b2f885e2392b0414a4f9589a4b1f/artichoke-backend/src/extn/core/array/mruby.rs#L68-L82
3. Expose the method to Ruby:
  https://github.com/artichoke/artichoke/blob/a2229d9de0a0b2f885e2392b0414a4f9589a4b1f/artichoke-backend/src/extn/core/array/mruby.rs#L14
4. Delete the pure Ruby implementation of `Array#clear`:
  https://github.com/artichoke/artichoke/blob/a2229d9de0a0b2f885e2392b0414a4f9589a4b1f/artichoke-backend/src/extn/core/array/mod.rs#L183-L185

**Comment by daegalus** [comment]
If its cool, I wouldn't mind taking a stab at this. Im no expert in either language, but definitely want to try, and this seems fairly simple.

**Comment by lopopolo** [comment]
Sounds great @Daegalus. I'll assign to you.
